CREATE TABLE companies (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150 CHAR) NOT NULL,
    normalized_name VARCHAR2(150 CHAR) NOT NULL,
    website VARCHAR2(1000 CHAR),
    industry VARCHAR2(150 CHAR),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_company_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE job_applications (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR2(150 CHAR) NOT NULL,
    job_url VARCHAR2(1000 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    source VARCHAR2(100 CHAR),
    location VARCHAR2(150 CHAR),
    applied_date DATE,
    company_id NUMBER(19,0) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_job_application_url UNIQUE (job_url),
    CONSTRAINT fk_job_application_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE application_notes (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER(19,0) NOT NULL,
    content VARCHAR2(2000 CHAR) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_note_application FOREIGN KEY (application_id) REFERENCES job_applications (id)
);

CREATE INDEX idx_job_application_status ON job_applications (status);
CREATE INDEX idx_job_app_applied_date ON job_applications (applied_date);
CREATE INDEX idx_job_application_company ON job_applications (company_id);
CREATE INDEX idx_note_application_created ON application_notes (application_id, created_at, id);
