CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    normalized_name VARCHAR(150) NOT NULL,
    website VARCHAR(1000),
    industry VARCHAR(150),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_company_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR(150) NOT NULL,
    job_url VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    source VARCHAR(100),
    location VARCHAR(150),
    applied_date DATE,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_job_application_url UNIQUE (job_url),
    CONSTRAINT fk_job_application_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE application_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_note_application FOREIGN KEY (application_id) REFERENCES job_applications (id)
);

CREATE INDEX idx_job_application_status ON job_applications (status);
CREATE INDEX idx_job_app_applied_date ON job_applications (applied_date);
CREATE INDEX idx_job_application_company ON job_applications (company_id);
CREATE INDEX idx_note_application_created ON application_notes (application_id, created_at, id);
